rets/client/table.py
rets/http/parsers/http.py
rets/http/parsers/parse.py

Rets has max row limitations, and will sometimes limit the number of results that it returns. The usual symptom here is that count > len(data)
It will indicate when this is out of sync in 2 ways 
- existence of maxrows tag
- rets-status 
This PR fixes the maxrows check and parses out rets-status when it exists

Add rets status and correct max rows

---

rets/http/client.py

Using get for search fails on GAMLS when the number of ids fetched is too big (~2000)

use http post for search requests

---

rets/client/client.py
rets/client/object_type.py
rets/client/resource.py
rets/client/resource_class.py
rets/client/table.py
rets/http/client.py

So we can avoid unnecessary login and get_metadata transactions if we already have the session cookie, capability URLs, and the metadata.

Enable RetsClient instantiation from metadata dict

---

rets/http/parsers/http.py

For when the response doesn't include any encoding headers

Use default utf-8 encoding when parsing multipart responses

---

.bumpversion.cfg
.travis.yml
README.md
setup.py

Because the `typing` module was only added in 3.5.

Revise supported versions to 3.5 or later

---

rets/http/parsers/parse_object.py

Latest version of requests no longer has cgi module. Requests was just importing cgi from the standard library anyway.

Import cgi from standard library instead of requests

---

rets/client/decoder.py
tests/client/decoder_test.py

Running into an MLS that formats the dates differently to the specification by using a space separator. This is a quick fix to ensure the parser continues working here and haven't worried about entirely incorrect formats that might encounter a space here because `udatetime` strictly adheres to RFC3339, so it shouldn't be possible for the 1 character change to result in a valid datetime except in this scenario.

Replace space with `T` for datetime parser

---

setup.py

Old version can't parse:
udatetime.from_string('2018-08-21T21:06:06.2')

Fix the version of the udatetime

---

rets/errors.py
rets/http/parsers/parse_object.py
tests/http/parsers/parse_object_test.py

Raise a catchable error when `headers['content-type']` is missing. While reviewing the code, I split the `Location` header response to exit earlier since the `content-type` header is not required on that code path. The next part will do the usual checks but also verify we have a `content-type` header. If not, we raise a `RetsContentTypeError` that contains the response and headers for easier debugging.

Raise error on invalid `content-type` response

---

rets/errors.py
rets/http/parsers/parse_object.py

Following up on https://github.com/opendoor-labs/rets/pull/35 to handle other missing required headers.

Add error for missing `content-id` or `object-id`

---

rets/http/parsers/parse_object.py
tests/http/parsers/parse_object_test.py

Improves upon https://github.com/opendoor-labs/rets/pull/36 by parsing the body when the response type is XML, instead of failing on invalid response.

Parse XML response before raising on bad headers

---

rets/client/decoder.py
tests/client/decoder_test.py

CARETS uses Number types in their columns which are just integers. This change adds support for them.

Add support for Number types

---

rets/http/parsers/parse.py
setup.py

While parsing some data from CARETS, we found a few invalid characters in the data that the basic XML parser couldn't handle. This change switches the parser to use `lxml` and skip invalid characters.

Use `lxml` to parse XML and handle invalid characters

---

rets/http/client.py

Title-cased keys for metadata requests are declared in RETS standard (https://www.nar.realtor/retsorg.nsf/retsproto1.7d6.pdf section 11.1.2) and were necessary for Victoria MLS RETS feed.
Both authentication methods were necessary for Paragon RETS feed (http://paragonconnect.paragonrels.com/rets/user-and-password-availability).
Fix UA authentication (add missing _Digest _ and fix missing session ID)

Fix metadata request and use all authentications if passwords are provided

---

rets/http/client.py

We found realtracs is responding with a `20502` ("Invalid Identifier" - The identifier is not known inside the specified resource) when asking for metadata that doesn't exist (e.g. `METADATA-OBJECT` on `Agent` resource). Another workaround we should consider moving to is asking for `:*` (all resources) instead of a specific resource - it may optimize the number of round trip HTTP requets.

Handle `20502` in response for invalid metadata

---

rets/http/parsers/parse.py

I had an issue with KAR (Kootenay) RETS feed, where parsing failed on character 0xae (register mark in latin-1 encoding). This change fixed the issue, it's similar to this fix: https://github.com/opendoor-labs/rets/pull/17/files

Use response encoding with fallback to default

---

README.md
rets/client/record.py

There's been a few instances where the MLS `KeyField` has been incorrect and we need to override internally, using long hand accessors would avoid having to adds hacks around the automatic metadata usage in `rets`.

Delete resource key from record

---

rets/client/decoder.py
tests/client/decoder_test.py

Follow up to https://github.com/opendoor-labs/rets/pull/57. Index 10 may be out of range (due to the check below it). Invert the checks instead, adding the time then checking for a space.

Fix date from RETS

---

rets/client/decoder.py

Now we know the field `ORM4_WID` that's problematic.
Old error
`invalid literal for int() with base 10: '5.6'`
new error:
`ValueError: Error decoding field ORM4_WID with value 5.6. Error: invalid literal for int() with base 10: '5.6'`

Update error message when decoding wrong data type

---

rets/http/client.py
rets/http/parsers/parse.py
tests/client/request_test.py

I found one MLS RETS implementations will raise an error if you pass `RETS-UA-Authorization` where there is a User-Agent but not a User-Agent-Password. Most MLS don't have an issue with it, so default should be to send RETS-UA-Authorization.
Additionally, this MLS also returns non-standard encoding in case of errors, but otherwise returns standard non-problematic encoding if the response is normal. Therefore, I added an exception in the case of non-standard response to parse it as raw binary, which is successful.
Details from RETS 1.7.2 specification regarding RETS-UA-Authorization:

Option to not pass 'RETS-UA-Authorization', and parse non-utf8 xml

---

setup.py

There is a dependency in `install_requires` in `setup.py` on `docopts`, but this package is not at all dependent on `docopts`. It is only lightly used in `bin/deploy` script which is not part of the library itself.
This causes problems in some popular dependency resolvers like [`pip-compile`](https://github.com/jazzband/pip-tools) as [`docopts`](https://github.com/docopt/docopts) moved from Python to Go in v0.6.2 and stopped publishing packages to PyPI. The unnecessary dependency on `docopts` Python package here brings in v0.6.1 which also brings in a pinned dependency on [`docopt`](https://github.com/docopt/docopt) (no 's') v0.6.1, which has been outdated since 2014 with v0.6.2 release.
Therefore, using any other Python library that depends on `docopt > 0.6.1` cannot be used alongside …

remove docopts from install_requires

---

setup.py

Closes #59 
Updated udatetime dependency to 0.0.17 to be able to build this repo on newer versions of Python (tested on 3.10)
I've run this on Python3.10, retrieved some items from a MLS and ensured that datetime fields are parsed and parsed correctly. 
There are no major changes to the udatetime library, so, IMO, this will do.
Also I've run tests and they passed:
```
================================ test session starts =================================
platform linux -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/olekthunder/git-repos/opendoor-rets
collected 25 items
tests/client/decoder_test.py ......                                            [ 24%]
tests/client/http_client_test.py .                                             [ 28%]
tests/client/request_test.py .. …
```

Update udatetime to 0.0.17
